import { ProductData } from "@/app/products/[id]/page";
import {
  Briefcase,
  Building,
  HardHat,
  Home,
  Landmark,
  Layers,
  User,
  CreditCard,
  AlertTriangle,
  GitCommit,
  Scale,
} from "lucide-react";

export const servicesData = [
  {
    slug: "cash-credit-limit",
    title: "Cash Credit Limit",
    desc: "Flexible working capital facility to manage business cash flow needs.",
    icon: CreditCard,
    price: "Low Premium",
    counter: "+800 Active",
    img: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "overdraft-limit",
    title: "Over Draft Limit",
    desc: "Short-term credit facility allowing withdrawals beyond available account balance.",
    icon: Briefcase,
    price: "Flexible Cap",
    counter: "+420 Active",
    img: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "home-loan",
    title: "Home Loan",
    desc: "Long-term financing facility for purchasing, constructing, or renovating homes.",
    icon: Home,
    price: "Prime Rates",
    counter: "+840 Profiles",
    img: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "personal-loan",
    title: "Personal Loan",
    desc: "Unsecured loan for personal needs with fixed repayment terms.",
    icon: User,
    price: "Instant Disp",
    counter: "+3.1k Users",
    img: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "business-loan",
    title: "Business Loan",
    desc: "Flexible funding solution to meet business operational and expansion needs.",
    icon: Layers,
    price: "Custom Cap",
    counter: "+410 Agencies",
    img: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "project-loan",
    title: "Project Loan",
    desc: "Funding facility for financing new projects, infrastructure, or business expansion.",
    icon: HardHat,
    price: "Project Plan",
    counter: "+150 Projects",
    img: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "loan-against-property",
    title: "Loan Against Property",
    desc: "Secured loan availed by mortgaging residential or commercial property.",
    icon: Building,
    price: "Asset Value",
    counter: "+680 Assets",
    img: "https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "govt-subsidy-scheme",
    title: "Govt Subsidy",
    desc: "Financial assistance from government schemes to support eligible businesses.",
    icon: Landmark,
    price: "Govt Verified",
    counter: "+920 Grants",
    img: "/govt-subsidy.webp",
  },
  {
    slug: "npa-ots-funding",
    title: "NPA & OTS Funding",
    desc: "Solutions for stressed & OTS accounts.",
    icon: AlertTriangle,
    price: "Stressed Capital",
    counter: "+250 Accounts",
    img: "https://images.unsplash.com/photo-1599050751795-6cdaafbc2319?q=80&w=1200&auto=format&fit=crop",
  },
  {
    slug: "bridge-finance",
    title: "Bridge Finance",
    desc: "Short-term funding for immediate needs.",
    icon: GitCommit,
    price: "Short-Term",
    counter: "+310 Deals",
    img: "/bridge-finance.webp",
  },
  {
    slug: "stressed-asset-finance",
    title: "Stressed Asset Finance",
    desc: "Resolution & financing for distressed assets.",
    icon: Scale,
    price: "Turnaround",
    counter: "+180 Recoveries",
    img: "/stressed-asset-finance.webp",
  },
];

export const productsData: Record<string, ProductData> = {
  "cash-credit-limit": {
    slug: "cash-credit-limit",
    icon: CreditCard,
    badge: "Working Capital",
    tag: "CC Limit",
    title: "Cash Credit Limit",
    tagline: "Revolving Credit for Your Business!",
    heroDesc:
      "Our Cash Credit (CC) facility provides a revolving credit line that helps you manage working capital, cover short-term expenses, and grow your business without disruption.",
    about:
      "A Cash Credit (CC) limit is a short-term credit facility extended by banks to businesses. It allows you to withdraw funds up to a sanctioned limit and repay flexibly. Interest is charged only on the amount utilized, making it a cost-effective solution for managing day-to-day business operations. Whether you need to cover short-term expenses, manage cash flow, or seize new business opportunities, our CC facility provides the flexibility you need.",
    benefitsTitle: "Benefits of Cash Credit Limit",
    benefits: [
      "Revolving Credit Line – Withdraw and repay as needed without reapplying",
      "Pay Interest Only on Usage – Cost-effective borrowing at all times",
      "Flexible Repayment – Repay at your convenience without fixed EMIs",
      "Supports Business Growth – Helps manage working capital smoothly",
      "Minimal Documentation & Quick Approval – Fast processing for hassle-free borrowing",
    ],
    img: "/cash-credit-limit.webp",
    accentColor: "var(--color-brand)",
  },
  "overdraft-limit": {
    slug: "overdraft-limit",
    icon: Briefcase,
    badge: "Working Capital",
    tag: "OD Limit",
    title: "Over Draft Limit",
    tagline: "Instant Liquidity When You Need It!",
    heroDesc:
      "Our Over Draft (OD) facility lets your business withdraw beyond the available account balance, providing instant access to funds for urgent financial needs.",
    about:
      "An Over Draft (OD) limit is a credit facility linked to your current account that allows you to overdraw beyond your balance up to a pre-approved limit. It's ideal for businesses that face sudden cash flow gaps and need instant liquidity without lengthy loan processing. Our team of experts ensures that you get the best OD facility, guiding you through every step of the process.",
    benefitsTitle: "Benefits of Over Draft Limit",
    benefits: [
      "Instant Access to Funds – Withdraw beyond your balance anytime",
      "Pay Interest Only on Usage – Cost-effective short-term borrowing",
      "Flexible Repayment – No fixed EMIs, repay as funds become available",
      "Linked to Current Account – Seamless integration with your business account",
      "Minimal Documentation & Quick Approval – Fast processing for hassle-free borrowing",
    ],
    img: "/over-draft-limit.webp",
    accentColor: "var(--color-brand)",
  },
  "home-loan": {
    slug: "home-loan",
    icon: Home,
    badge: "Real Estate",
    tag: "Home Loan",
    title: "Home Loan",
    tagline: "Make Your Dream Home a Reality!",
    heroDesc:
      "Owning a home is a significant milestone, and we are here to make it happen with easy, affordable, and hassle-free home loan solutions.",
    about:
      "Buying a home is a life-changing decision, and we are here to simplify the process for you. With our tailor-made home loan solutions, you can finance your dream home without any financial stress. Whether you're a first-time homebuyer or looking to invest in another property, we provide flexible repayment options, competitive interest rates, and a hassle-free loan application process. Our team of experts ensures that you get the best home loan offer, guiding you through every step of the process—from selecting the right loan plan to completing documentation and disbursement.",
    benefitsTitle: "Why Choose Our Home Loan?",
    benefits: [
      "Low-Interest Rates – Affordable EMIs to fit your budget",
      "Flexible Repayment Tenure – Choose a repayment plan that suits you",
      "High Loan Amounts – Finance up to 90% of your home's value",
      "Quick Approvals – Fast processing with minimal documentation",
      "Minimal Documentation & Quick Approval – Fast processing for hassle-free borrowing",
    ],
    img: "/home-loan.webp",
    accentColor: "var(--color-accent-teal)",
  },
  "personal-loan": {
    slug: "personal-loan",
    icon: User,
    badge: "Personal Finance",
    tag: "Personal Loan",
    title: "Personal Loan",
    tagline: "Freedom to Manage Your Finances!",
    heroDesc:
      "A Personal Loan gives you the freedom to manage your finances without any restrictions — medical emergencies, weddings, travel, education, or any urgent need.",
    about:
      "Our simple application process ensures that you get your loan approved without lengthy paperwork. With minimal documentation and a quick eligibility check, your loan is processed in no time. Our team of experts ensures that you get the best Personal loan offer, guiding you through every step of the process—from selecting the right loan plan to completing documentation and disbursement.",
    benefitsTitle: "Why Choose Our Personal Loan?",
    benefits: [
      "Instant Approval & Quick Disbursal – Get funds in your account within hours",
      "No Collateral Required – 100% unsecured loan with no security needed",
      "Low-Interest Rates – Affordable EMIs for easy repayment",
      "Minimal Documentation – Simple and hassle-free process",
      "Flexible Tenure – Repay in easy installments ranging from 12 to 60 months",
      "Multi-Purpose Loan – Use it for any personal financial need",
    ],
    whoCanApply: [
      "Salaried professionals",
      "Self-employed individuals",
      "Business owners",
      "Government employees",
    ],
    img: "/persoanl-loan.webp",
    accentColor: "var(--color-accent-yellow)",
  },
  "business-loan": {
    slug: "business-loan",
    icon: Layers,
    badge: "Business Finance",
    tag: "Business Loan",
    title: "Business Loan",
    tagline: "Fuel Your Business Growth!",
    heroDesc:
      "Running a business requires capital — whether expanding operations, purchasing new equipment, or meeting working capital needs. Our Business Loan solutions provide quick access to funds.",
    about:
      "Take your business to the next level with our easy-to-access Business Loans and focus on what matters most — your growth and success. Our team of experts ensures that you get the best Business loan offer, guiding you through every step of the process — from selecting the right loan plan to completing documentation and disbursement.",
    benefitsTitle: "Why Choose Our Business Loan?",
    benefits: [
      "Fast Processing & Quick Disbursal – Get the funds you need when you need them",
      "Flexible Loan Amounts – Borrow as per your business requirements",
      "Competitive Interest Rates – Affordable EMI options tailored to your budget",
      "No Collateral Required – Unsecured loan options with easy eligibility",
      "Flexible Repayment Tenure – Choose a repayment period that works for your cash flow",
      "Minimal Documentation – A quick and hassle-free application process",
    ],
    extraSections: [
      {
        title: "Benefits of Our Business Loan",
        items: [
          "Expand Your Business – Set up new branches, hire staff, or invest in machinery",
          "Boost Your Working Capital – Cover daily operational costs smoothly",
          "Purchase Equipment or Inventory – Buy the resources needed without financial strain",
          "Invest in Marketing & Growth – Fund campaigns or launch new products and services",
        ],
      },
    ],
    whoCanApply: [
      "Small and medium-sized enterprises (SMEs)",
      "Startups looking for initial funding",
      "Established businesses needing expansion capital",
      "Entrepreneurs with innovative business ideas",
    ],
    img: "/business-loan.webp",
    accentColor: "var(--color-accent-blue)",
  },
  "project-loan": {
    slug: "project-loan",
    icon: HardHat,
    badge: "Project Finance",
    tag: "Project Loan",
    title: "Project Loan",
    tagline: "Scale Your Vision with Confidence!",
    heroDesc:
      "Whether you're launching a new venture, expanding an existing business, or funding large-scale projects, we provide high-value loans with flexible terms and quick approvals.",
    about:
      "Project loans are designed for ambitious entrepreneurs and businesses that need significant capital to bring their vision to life. Our expert team guides you from loan selection through disbursement, ensuring that every step is simple, transparent, and tailored to your goals.",
    benefitsTitle: "Why Choose Our Project Loan?",
    benefits: [
      "Fast Processing & Quick Disbursal – Get the funds you need when you need them",
      "Flexible Loan Amounts – Borrow as per your project requirements",
      "Competitive Interest Rates – Affordable EMI options tailored to your budget",
      "No Collateral Required – Unsecured loan options with easy eligibility",
      "Flexible Repayment Tenure – Choose a repayment period that works for your cash flow",
      "Minimal Documentation – A quick and hassle-free application process",
    ],
    whoCanApply: [
      "Small and medium-sized enterprises (SMEs)",
      "Startups looking for initial funding",
      "Established businesses needing expansion capital",
      "Entrepreneurs with innovative business ideas",
    ],
    img: "/project-loan.webp",
    accentColor: "var(--color-accent-indigo)",
  },
  "loan-against-property": {
    slug: "loan-against-property",
    icon: Building,
    badge: "Secured Lending",
    tag: "LAP",
    title: "Loan Against Property",
    tagline: "Unlock the Value of Your Asset!",
    heroDesc:
      "A Loan Against Property (LAP) lets you leverage the value of your property to meet your financial needs — business expansion, education, medical emergencies, and more.",
    about:
      "Unlock the potential of your property and meet your financial goals with a Loan Against Property. Our team of experts ensures that you get the best Loan Against Property offer, guiding you through every step of the process — from selecting the right loan plan to completing documentation and disbursement.",
    benefitsTitle: "Why Choose a Loan Against Property?",
    benefits: [
      "High Loan Amounts – Borrow a substantial sum against the value of your property",
      "Competitive Interest Rates – Lower interest compared to unsecured loans",
      "Flexible Repayment Tenure – Choose a repayment period that suits your financial capacity",
      "Minimal Documentation – Quick approval with minimal paperwork",
      "Tax Benefits – Enjoy potential tax savings on the interest paid under Section 24",
    ],
    extraSections: [
      {
        title: "Types of Properties Accepted",
        items: [
          "Residential Properties – Own house, flat, or apartment",
          "Commercial Properties – Offices, retail spaces, or commercial buildings",
          "Industrial Properties – Factories, warehouses, and industrial land",
        ],
      },
      {
        title: "Benefits of Loan Against Property",
        items: [
          "Quick Access to Funds – Get funds faster than unsecured loans",
          "Use for Any Purpose – Personal needs, business, medical expenses, education, etc.",
          "No Restriction on Use – Complete freedom on how you use the loan amount",
          "Retain Ownership – Maintain full ownership of your property while accessing funds",
        ],
      },
    ],
    whoCanApply: [
      "Homeowners",
      "Business Owners",
      "Self-employed Individuals",
      "Salaried Professionals",
    ],
    img: "/loan-against-property.webp",
    accentColor: "var(--color-accent-brown)",
  },
  "govt-subsidy-scheme": {
    slug: "govt-subsidy-scheme",
    icon: Landmark,
    badge: "Government Programs",
    tag: "Govt Subsidy",
    title: "Government Subsidy",
    tagline: "Unlock the Benefits of Government Schemes!",
    heroDesc:
      "Navigating through the complexities of Government Subsidy can be challenging, but with the right guidance, you can make the most of opportunities available.",
    about:
      "As expert consultants, we help individuals and businesses understand, apply for, and benefit from various subsidy schemes, grants, and financial support programs launched by the government. Let us help you unlock the full potential of available government subsidies and grants, making your business or personal goals easier to achieve.",
    benefitsTitle: "Why Choose Our Consultancy?",
    benefits: [
      "Expert Guidance – Consultants well-versed with the latest government schemes",
      "Seamless Application Process – Full guidance with all documentation requirements met",
      "Maximized Benefits – Secure maximum benefits from government schemes",
      "Timely Assistance – Never miss application deadlines",
      "Customized Solutions – Personalized consultancy for your specific needs",
    ],
    extraSections: [
      {
        title: "Government Subsidy We Assist With",
        items: [
          "Start-Up Subsidies – Financial assistance for new businesses and entrepreneurs",
          "MSME Subsidy Schemes – Funding support for small and medium enterprises",
          "Housing Subsidies – Benefits for building, buying, or renovating homes",
          "Education and Training Grants – Financial assistance for education and skill development",
          "Agriculture Subsidies – Support for farmers to improve productivity",
          "Electric Vehicle (EV) Subsidies – Assistance for purchasing electric vehicles",
        ],
      },
    ],
    whoCanApply: [
      "Entrepreneurs & Startups",
      "Small and Medium Enterprises (SMEs)",
      "Farmers & Agricultural Businesses",
      "Educational Institutions",
      "Homebuyers & Builders",
      "Individuals seeking government support",
    ],
    img: "/govt-subsidy.webp",
    accentColor: "var(--color-accent-mint)",
  },
  "npa-ots-funding": {
    slug: "npa-ots-funding",
    icon: AlertTriangle,
    badge: "Specialized Funding",
    tag: "NPA & OTS",
    title: "NPA & OTS Funding",
    tagline: "Solutions for Stressed & OTS Accounts!",
    heroDesc:
      "Financial assistance and structured funding solutions tailored to resolve Non-Performing Assets (NPA) and One-Time Settlement (OTS) accounts.",
    about:
      "NPA & OTS Funding is designed to support businesses and individuals facing severe financial stress. We provide strategic funding and expert advice to help you settle bank dues through One-Time Settlement schemes and bring your operations back on track.",
    benefitsTitle: "Why Choose NPA & OTS Funding?",
    benefits: [
      "Quick OTS Settlement Support – Capital assistance to settle NPA debts promptly",
      "Prevents Asset Auction – Safeguard your valuable collateral from bank recovery action",
      "Structured Repayment Plans – Tailored financing to match your recovery cash flows",
      "Expert Advisory – Professional guidance through complex bank negotiations",
    ],
    img: "/npa-ots-funding.webp",
    accentColor: "var(--color-accent-red)",
  },
  "bridge-finance": {
    slug: "bridge-finance",
    icon: GitCommit,
    badge: "Short-Term Financing",
    tag: "Bridge Finance",
    title: "Bridge Finance",
    tagline: "Short-Term Funding for Immediate Needs!",
    heroDesc:
      "Interim, short-term funding options designed to bridge the gap between immediate capital requirements and long-term financing solutions.",
    about:
      "Bridge Finance provides fast and flexible short-term capital when time is critical. Whether you are awaiting major fund disbursements, property sales, or long-term loan approvals, our bridge funding ensures your operations and projects never stop.",
    benefitsTitle: "Benefits of Bridge Finance",
    benefits: [
      "Fast Capital Access – Urgent disbursement to meet tight financial deadlines",
      "Flexible Short-Term Terms – Customized to match your expected long-term cash inflows",
      "Seamless Liquidity – Prevents project delays during financing transitions",
      "Minimal Hurdles – Streamlined processing for immediate needs",
    ],
    img: "/bridge-finance.webp",
    accentColor: "var(--color-accent-orange)",
  },
  "stressed-asset-finance": {
    slug: "stressed-asset-finance",
    icon: Scale,
    badge: "Asset Resolution",
    tag: "Stressed Assets",
    title: "Stressed Asset Finance",
    tagline: "Resolution & Financing for Distressed Assets!",
    heroDesc:
      "Tailored restructuring and financing solutions focused on reviving, restoring, and maximizing the value of distressed assets and businesses.",
    about:
      "Stressed Asset Finance provides capital and debt restructuring for businesses going through liquidity crunch or operational revival. We help turn distressed assets into profitable ventures by offering customized funding structures and resolution strategies.",
    benefitsTitle: "Why Opt for Stressed Asset Finance?",
    benefits: [
      "Business Turnaround Support – Infuse capital to revive struggling operations",
      "Custom Restructuring Solutions – Tailored financial structures suited to asset potential",
      "Debt Optimization – Reduce financial burden through strategic debt resolution",
      "Value Preservation – Protect and optimize long-term asset worth",
    ],
    img: "/stressed-asset-finance.webp",
    accentColor: "var(--color-accent-purple)",
  },
};
