import { ProductData } from "@/app/products/[id]/page";
import {
  Briefcase,
  Building,
  HardHat,
  Home,
  Landmark,
  Layers,
  User,
} from "lucide-react";

export const servicesData = [
  {
    slug: "od-cc-limit",
    title: "OD / CC Limit",
    desc: "Need working capital for your business? Our Overdraft (OD) and Cash Credit (CC) facilities provide seamless financial support to keep your business running smoothly.",
    icon: Briefcase,
    price: "Low Premium",
    counter: "+1.2k Active",
    img: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=400&q=80",
  },
  {
    slug: "home-loan",
    title: "Home Loan",
    desc: "Our home loan solutions come with low-interest rates, flexible repayment options, and quick approvals, so you can move into your dream home.",
    icon: Home,
    price: "Prime Rates",
    counter: "+840 Profiles",
    img: "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&w=400&q=80",
  },
  {
    slug: "personal-loan",
    title: "Personal Loan",
    desc: "Our Personal Loan solutions help you cover medical emergencies, travel, education, wedding expenses, or any urgent needs with fast approvals & minimal paperwork.",
    icon: User,
    price: "Instant Disp",
    counter: "+3.1k Users",
    img: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=400&q=80",
  },
  {
    slug: "business-loan",
    title: "Business Loan",
    desc: "Our Business Loan solutions provide quick funding, low-interest rates, and flexible repayment options to support your entrepreneurial journey.",
    icon: Layers,
    price: "Custom Cap",
    counter: "+410 Agencies",
    img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=400&q=80",
  },
  {
    slug: "project-loan",
    title: "Project Loan",
    desc: "Whether you're launching a new venture, expanding an existing business, or funding large-scale projects, we provide high-value loans with flexible terms and quick approvals to support your goals.",
    icon: HardHat,
    price: "Project Plan",
    counter: "+150 Projects",
    img: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=400&q=80",
  },
  {
    slug: "loan-against-property",
    title: "Loan Against Property",
    desc: "Need funds for business expansion, education, medical emergencies, or personal needs? Get a high-value loan by leveraging your property at low interest rates and flexible repayment options.",
    icon: Building,
    price: "Asset Value",
    counter: "+680 Assets",
    img: "https://images.unsplash.com/photo-1582408921715-18e7806365c1?auto=format&fit=crop&w=400&q=80",
  },
  {
    slug: "govt-subsidy-scheme",
    title: "Govt Subsidy Scheme",
    desc: "Looking for expert guidance on government subsidies? We help businesses and individuals navigate and avail government subsidy schemes to reduce financial burdens and boost growth.",
    icon: Landmark,
    price: "Govt Verified",
    counter: "+920 Grants",
    img: "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=400&q=80",
  },
];

export const productsData: Record<string, ProductData> = {
  "od-cc-limit": {
    slug: "od-cc-limit",
    icon: Briefcase,
    badge: "Working Capital",
    tag: "OD / CC",
    title: "Overdraft & Cash Credit",
    tagline: "Flexible Funding for Your Business!",
    heroDesc:
      "Need working capital for your business? Our Overdraft (OD) and Cash Credit (CC) facilities provide seamless financial support to keep your business running smoothly.",
    about:
      "Running a business comes with unpredictable financial needs. Our Overdraft (OD) and Cash Credit (CC) facilities provide instant access to funds, helping you manage cash flow, meet working capital requirements, and grow your business without disruption. Whether you need to cover short-term expenses, manage cash flow, or seize new business opportunities, our OD & CC loans provide the flexibility you need.",
    benefitsTitle: "Benefits of OD & CC Loans",
    benefits: [
      "Instant Access to Funds – Withdraw money as needed",
      "Pay Interest Only on Usage – Cost-effective borrowing",
      "Flexible Repayment – Repay at your convenience",
      "Supports Business Growth – Helps manage working capital smoothly",
      "Minimal Documentation & Quick Approval – Fast processing for hassle-free borrowing",
    ],
    img: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80",
    accentColor: "var(--color-brand)",
  },
  "home-loan": {
    slug: "home-loan",
    icon: Home,
    badge: "Real Estate",
    tag: "Home Loan",
    title: "Home Loan",
    tagline: "Make Your Dream Home a Reality!",
    heroDesc:
      "Owning a home is a significant milestone, and we are here to make it happen with easy, affordable, and hassle-free home loan solutions.",
    about:
      "Buying a home is a life-changing decision, and we are here to simplify the process for you. With our tailor-made home loan solutions, you can finance your dream home without any financial stress. Whether you're a first-time homebuyer or looking to invest in another property, we provide flexible repayment options, competitive interest rates, and a hassle-free loan application process. Our team of experts ensures that you get the best home loan offer, guiding you through every step of the process—from selecting the right loan plan to completing documentation and disbursement.",
    benefitsTitle: "Why Choose Our Home Loan?",
    benefits: [
      "Low-Interest Rates – Affordable EMIs to fit your budget",
      "Flexible Repayment Tenure – Choose a repayment plan that suits you",
      "High Loan Amounts – Finance up to 90% of your home's value",
      "Quick Approvals – Fast processing with minimal documentation",
      "Minimal Documentation & Quick Approval – Fast processing for hassle-free borrowing",
    ],
    img: "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&w=900&q=80",
    accentColor: "var(--color-accent-teal)",
  },
  "personal-loan": {
    slug: "personal-loan",
    icon: User,
    badge: "Personal Finance",
    tag: "Personal Loan",
    title: "Personal Loan",
    tagline: "Freedom to Manage Your Finances!",
    heroDesc:
      "A Personal Loan gives you the freedom to manage your finances without any restrictions — medical emergencies, weddings, travel, education, or any urgent need.",
    about:
      "Our simple application process ensures that you get your loan approved without lengthy paperwork. With minimal documentation and a quick eligibility check, your loan is processed in no time. Our team of experts ensures that you get the best Personal loan offer, guiding you through every step of the process—from selecting the right loan plan to completing documentation and disbursement.",
    benefitsTitle: "Why Choose Our Personal Loan?",
    benefits: [
      "Instant Approval & Quick Disbursal – Get funds in your account within hours",
      "No Collateral Required – 100% unsecured loan with no security needed",
      "Low-Interest Rates – Affordable EMIs for easy repayment",
      "Minimal Documentation – Simple and hassle-free process",
      "Flexible Tenure – Repay in easy installments ranging from 12 to 60 months",
      "Multi-Purpose Loan – Use it for any personal financial need",
    ],
    whoCanApply: [
      "Salaried professionals",
      "Self-employed individuals",
      "Business owners",
      "Government employees",
    ],
    img: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=900&q=80",
    accentColor: "var(--color-accent-yellow)",
  },
  "business-loan": {
    slug: "business-loan",
    icon: Layers,
    badge: "Business Finance",
    tag: "Business Loan",
    title: "Business Loan",
    tagline: "Fuel Your Business Growth!",
    heroDesc:
      "Running a business requires capital — whether expanding operations, purchasing new equipment, or meeting working capital needs. Our Business Loan solutions provide quick access to funds.",
    about:
      "Take your business to the next level with our easy-to-access Business Loans and focus on what matters most — your growth and success. Our team of experts ensures that you get the best Business loan offer, guiding you through every step of the process — from selecting the right loan plan to completing documentation and disbursement.",
    benefitsTitle: "Why Choose Our Business Loan?",
    benefits: [
      "Fast Processing & Quick Disbursal – Get the funds you need when you need them",
      "Flexible Loan Amounts – Borrow as per your business requirements",
      "Competitive Interest Rates – Affordable EMI options tailored to your budget",
      "No Collateral Required – Unsecured loan options with easy eligibility",
      "Flexible Repayment Tenure – Choose a repayment period that works for your cash flow",
      "Minimal Documentation – A quick and hassle-free application process",
    ],
    extraSections: [
      {
        title: "Benefits of Our Business Loan",
        items: [
          "Expand Your Business – Set up new branches, hire staff, or invest in machinery",
          "Boost Your Working Capital – Cover daily operational costs smoothly",
          "Purchase Equipment or Inventory – Buy the resources needed without financial strain",
          "Invest in Marketing & Growth – Fund campaigns or launch new products and services",
        ],
      },
    ],
    whoCanApply: [
      "Small and medium-sized enterprises (SMEs)",
      "Startups looking for initial funding",
      "Established businesses needing expansion capital",
      "Entrepreneurs with innovative business ideas",
    ],
    img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80",
    accentColor: "var(--color-accent-blue)",
  },
  "project-loan": {
    slug: "project-loan",
    icon: HardHat,
    badge: "Project Finance",
    tag: "Project Loan",
    title: "Project Loan",
    tagline: "Scale Your Vision with Confidence!",
    heroDesc:
      "Whether you're launching a new venture, expanding an existing business, or funding large-scale projects, we provide high-value loans with flexible terms and quick approvals.",
    about:
      "Project loans are designed for ambitious entrepreneurs and businesses that need significant capital to bring their vision to life. Our expert team guides you from loan selection through disbursement, ensuring that every step is simple, transparent, and tailored to your goals.",
    benefitsTitle: "Why Choose Our Project Loan?",
    benefits: [
      "Fast Processing & Quick Disbursal – Get the funds you need when you need them",
      "Flexible Loan Amounts – Borrow as per your project requirements",
      "Competitive Interest Rates – Affordable EMI options tailored to your budget",
      "No Collateral Required – Unsecured loan options with easy eligibility",
      "Flexible Repayment Tenure – Choose a repayment period that works for your cash flow",
      "Minimal Documentation – A quick and hassle-free application process",
    ],
    whoCanApply: [
      "Small and medium-sized enterprises (SMEs)",
      "Startups looking for initial funding",
      "Established businesses needing expansion capital",
      "Entrepreneurs with innovative business ideas",
    ],
    img: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=900&q=80",
    accentColor: "var(--color-accent-indigo)",
  },
  "loan-against-property": {
    slug: "loan-against-property",
    icon: Building,
    badge: "Secured Lending",
    tag: "LAP",
    title: "Loan Against Property",
    tagline: "Unlock the Value of Your Asset!",
    heroDesc:
      "A Loan Against Property (LAP) lets you leverage the value of your property to meet your financial needs — business expansion, education, medical emergencies, and more.",
    about:
      "Unlock the potential of your property and meet your financial goals with a Loan Against Property. Our team of experts ensures that you get the best Loan Against Property offer, guiding you through every step of the process — from selecting the right loan plan to completing documentation and disbursement.",
    benefitsTitle: "Why Choose a Loan Against Property?",
    benefits: [
      "High Loan Amounts – Borrow a substantial sum against the value of your property",
      "Competitive Interest Rates – Lower interest compared to unsecured loans",
      "Flexible Repayment Tenure – Choose a repayment period that suits your financial capacity",
      "Minimal Documentation – Quick approval with minimal paperwork",
      "Tax Benefits – Enjoy potential tax savings on the interest paid under Section 24",
    ],
    extraSections: [
      {
        title: "Types of Properties Accepted",
        items: [
          "Residential Properties – Own house, flat, or apartment",
          "Commercial Properties – Offices, retail spaces, or commercial buildings",
          "Industrial Properties – Factories, warehouses, and industrial land",
        ],
      },
      {
        title: "Benefits of Loan Against Property",
        items: [
          "Quick Access to Funds – Get funds faster than unsecured loans",
          "Use for Any Purpose – Personal needs, business, medical expenses, education, etc.",
          "No Restriction on Use – Complete freedom on how you use the loan amount",
          "Retain Ownership – Maintain full ownership of your property while accessing funds",
        ],
      },
    ],
    whoCanApply: [
      "Homeowners",
      "Business Owners",
      "Self-employed Individuals",
      "Salaried Professionals",
    ],
    img: "https://images.unsplash.com/photo-1582408921715-18e7806365c1?auto=format&fit=crop&w=900&q=80",
    accentColor: "var(--color-accent-brown)",
  },
  "govt-subsidy-scheme": {
    slug: "govt-subsidy-scheme",
    icon: Landmark,
    badge: "Government Programs",
    tag: "Govt Subsidy",
    title: "Government Subsidy Scheme Consultant",
    tagline: "Unlock the Benefits of Government Schemes!",
    heroDesc:
      "Navigating through the complexities of Government Subsidy Schemes can be challenging, but with the right guidance, you can make the most of opportunities available.",
    about:
      "As expert consultants, we help individuals and businesses understand, apply for, and benefit from various subsidy schemes, grants, and financial support programs launched by the government. Let us help you unlock the full potential of available government subsidies and grants, making your business or personal goals easier to achieve.",
    benefitsTitle: "Why Choose Our Consultancy?",
    benefits: [
      "Expert Guidance – Consultants well-versed with the latest government schemes",
      "Seamless Application Process – Full guidance with all documentation requirements met",
      "Maximized Benefits – Secure maximum benefits from government schemes",
      "Timely Assistance – Never miss application deadlines",
      "Customized Solutions – Personalized consultancy for your specific needs",
    ],
    extraSections: [
      {
        title: "Government Subsidy Schemes We Assist With",
        items: [
          "Start-Up Subsidies – Financial assistance for new businesses and entrepreneurs",
          "MSME Subsidy Schemes – Funding support for small and medium enterprises",
          "Housing Subsidies – Benefits for building, buying, or renovating homes",
          "Education and Training Grants – Financial assistance for education and skill development",
          "Agriculture Subsidies – Support for farmers to improve productivity",
          "Electric Vehicle (EV) Subsidies – Assistance for purchasing electric vehicles",
        ],
      },
    ],
    whoCanApply: [
      "Entrepreneurs & Startups",
      "Small and Medium Enterprises (SMEs)",
      "Farmers & Agricultural Businesses",
      "Educational Institutions",
      "Homebuyers & Builders",
      "Individuals seeking government support",
    ],
    img: "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=900&q=80",
    accentColor: "var(--color-accent-mint)",
  },
};
